import { useEffect, useState } from "react";
import API from "../../api/axios.jsx";

const terms = ["First Term", "Second Term", "Third Term"];
const escapeHtml = (value = "") => String(value).replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");

export default function ClassScoreSheet() {
  const [term, setTerm] = useState(terms[0]); const [sheet, setSheet] = useState(null); const [message, setMessage] = useState(""); const [loading, setLoading] = useState(true);
  const load = async () => { try { setLoading(true); const result = await API.get(`/subject-scores/teacher/class-scoresheet?term=${encodeURIComponent(term)}`); setSheet(result.data); setMessage(""); } catch (e) { setSheet(null); setMessage(e.response?.data?.message || "Unable to load class scoresheet."); } finally { setLoading(false); } };
  useEffect(() => { load(); }, [term]);
  const print = async () => { try { const result = await API.get(`/subject-scores/teacher/class-scoresheet/print?term=${encodeURIComponent(term)}`); const data = result.data; const popup = window.open("", "_blank", "noopener,noreferrer"); if (!popup) return setMessage("Allow pop-ups to print the broadsheet."); const headers = data.subjects.map((subject) => `<th>${escapeHtml(subject.name)}</th>`).join(""); const rows = data.students.map((student, index) => `<tr><td>${index + 1}</td><td>${escapeHtml(student.full_name)}</td><td>${escapeHtml(student.admission_no || "")}</td>${student.subjects.map((subject) => `<td>${subject.total ?? "-"}</td>`).join("")}</tr>`).join(""); popup.document.write(`<!doctype html><html><head><title>${escapeHtml(data.class_record.name)} Broadsheet</title><style>body{font-family:Arial,sans-serif;padding:24px;color:#111}h1,h2,p{text-align:center;margin:6px}table{width:100%;border-collapse:collapse;margin-top:20px;font-size:11px}th,td{border:1px solid #222;padding:6px;text-align:center}th{background:#eee}td:nth-child(2){text-align:left}@media print{body{padding:0}}</style></head><body><h1>Golden Castle International School</h1><h2>${escapeHtml(data.class_record.name).toUpperCase()} Class Broadsheet</h2><p>${escapeHtml(data.class_record.session)} — ${escapeHtml(data.term)} | Form Teacher: ${escapeHtml(data.teacher.full_name)}</p><table><thead><tr><th>S/N</th><th>Student</th><th>Admission No.</th>${headers}</tr></thead><tbody>${rows}</tbody></table><p style="margin-top:45px">Form Teacher Signature: ____________________ &nbsp;&nbsp; School Authority: ____________________</p><script>window.onload=()=>window.print()</script></body></html>`); popup.document.close(); } catch (e) { setMessage(e.response?.data?.message || "Broadsheet printing is not available."); } };
  return <div className="px-6 py-8 lg:px-10"><h2 className="text-3xl font-extrabold text-secondary">Class Scoresheet</h2><p className="mt-3 text-secondary/75">Review all subject-teacher submissions for your assigned class. Printing is enabled only when every score is submitted or locked.</p>{message && <p className="mt-5 rounded-lg bg-red-500/10 p-4 font-semibold text-red-700">{message}</p>}<div className="mt-8 flex flex-wrap gap-4 rounded-xl bg-secondary p-5 shadow-lg"><select value={term} onChange={(e) => setTerm(e.target.value)} className="rounded-lg border border-primary/10 bg-primary/5 px-4 py-3 text-primary">{terms.map((item) => <option key={item}>{item}</option>)}</select><button disabled={!sheet?.complete || loading} onClick={print} className="rounded-lg bg-button px-5 py-3 font-bold text-secondary disabled:cursor-not-allowed disabled:opacity-50">Print final broadsheet</button></div>{sheet && <><div className={`mt-5 rounded-lg p-4 font-semibold ${sheet.complete ? "bg-green-500/10 text-green-700" : "bg-amber-500/10 text-amber-800"}`}>{sheet.complete ? "Ready to print: all subject scores are submitted or locked." : `Printing blocked: ${sheet.message}`}</div><section className="mt-8 overflow-hidden rounded-xl bg-secondary shadow-lg"><div className="overflow-x-auto"><table className="min-w-full"><thead className="bg-primary text-left text-xs font-bold uppercase text-secondary"><tr><th className="px-5 py-4">Student</th>{sheet.subjects.map((subject) => <th key={subject._id} className="px-5 py-4">{subject.name}</th>)}</tr></thead><tbody>{sheet.students.map((student) => <tr key={student._id} className="border-b border-primary/10 text-primary"><td className="px-5 py-4 font-semibold">{student.full_name}<span className="block text-xs text-primary/60">{student.admission_no}</span></td>{student.subjects.map((subject) => <td key={subject.class_subject} className="px-5 py-4"><b>{subject.total ?? "—"}</b><span className={`ml-2 text-xs ${["submitted", "locked"].includes(subject.status) ? "text-green-700" : "text-amber-700"}`}>{subject.status}</span></td>)}</tr>)}</tbody></table></div></section>{!sheet.complete && sheet.incomplete.length > 0 && <p className="mt-4 text-sm text-secondary/75">Missing or draft scores: {sheet.incomplete.slice(0, 5).map((item) => `${item.student} — ${item.subject}`).join("; ")}{sheet.incomplete.length > 5 ? ` and ${sheet.incomplete.length - 5} more.` : ""}</p>}</>}</div>;
}
