import { useEffect, useState } from "react";
import API from "../../api/axios.jsx";

export default function SubjectScores() {
  const [books, setBooks] = useState([]); const [bookId, setBookId] = useState(""); const [term, setTerm] = useState("First Term"); const [data, setData] = useState(null); const [message, setMessage] = useState(""); const [saving, setSaving] = useState(false);
  useEffect(() => { API.get("/subject-scores/teacher/books").then((r) => { setBooks(r.data || []); if (r.data?.[0]) setBookId(r.data[0]._id); }); }, []);
  useEffect(() => { if (bookId) API.get(`/subject-scores/book?class_subject=${bookId}&term=${encodeURIComponent(term)}`).then((r) => setData(r.data)).catch((e) => setMessage(e.response?.data?.message || "Unable to load score book.")); }, [bookId, term]);
  const update = (id, field, value) => setData((current) => ({ ...current, students: current.students.map((student) => student._id === id ? { ...student, score: { ...(student.score || {}), [field]: value } } : student) }));
  const save = async (submit) => { if (!data) return; setSaving(true); try { await API.put("/subject-scores/book", { class_subject: bookId, term, submit, scores: data.students.map((s) => ({ student: s._id, first_ca: s.score?.first_ca ?? 0, second_ca: s.score?.second_ca ?? 0, exam: s.score?.exam ?? 0 })) }); setMessage(submit ? "Scores submitted for admin review." : "Draft saved."); if (bookId) setData((await API.get(`/subject-scores/book?class_subject=${bookId}&term=${encodeURIComponent(term)}`)).data); } catch (e) { setMessage(e.response?.data?.message || "Unable to save scores."); } finally { setSaving(false); } };
  const input = "w-24 rounded border border-primary/15 bg-primary/5 px-2 py-2 text-primary outline-none focus:border-button";
  const policy = data?.subject?.assessment_policy || { first_ca_max: 20, second_ca_max: 20, exam_max: 60 };
  const components = [["first_ca", "CA1", policy.first_ca_max], ["second_ca", "CA2", policy.second_ca_max], ["exam", "Exam", policy.exam_max]];
  return <div className="px-6 py-8 lg:px-10"><h2 className="text-3xl font-extrabold text-secondary">Subject Scores</h2><p className="mt-3 text-secondary/75">Enter scores against the assessment policy set for this subject. The system totals each subject out of 100.</p>{message && <p className="mt-5 rounded-lg bg-primary/10 p-4 font-semibold text-primary">{message}</p>}<div className="mt-8 grid gap-4 rounded-xl bg-secondary p-5 shadow-lg md:grid-cols-2"><select className="rounded-lg border border-primary/10 bg-primary/5 px-4 py-3 text-primary" value={bookId} onChange={(e) => setBookId(e.target.value)}>{books.length === 0 && <option>No subject assignments</option>}{books.map((b) => <option key={b._id} value={b._id}>{b.class_record?.name?.toUpperCase()} — {b.subject_record?.name || b.subject}</option>)}</select><select className="rounded-lg border border-primary/10 bg-primary/5 px-4 py-3 text-primary" value={term} onChange={(e) => setTerm(e.target.value)}><option>First Term</option><option>Second Term</option><option>Third Term</option></select></div>{data && <section className="mt-8 overflow-hidden rounded-xl bg-secondary shadow-lg"><div className="overflow-x-auto"><table className="min-w-full"><thead className="bg-primary text-left text-xs font-bold uppercase text-secondary"><tr><th className="px-5 py-4">Student</th>{components.map(([, label, max]) => <th key={label} className="px-5 py-4">{label} /{max}</th>)}<th className="px-5 py-4">Total /100</th></tr></thead><tbody>{data.students.map((s) => { const total = Number(s.score?.first_ca || 0) + Number(s.score?.second_ca || 0) + Number(s.score?.exam || 0); const locked = s.score?.status === "locked"; return <tr key={s._id} className="border-b border-primary/10 text-primary"><td className="px-5 py-4 font-semibold">{s.full_name}<span className="block text-xs text-primary/60">{s.admission_no}</span></td>{components.map(([field,, max]) => <td key={field} className="px-5 py-4"><input className={input} type="number" min="0" max={max} disabled={locked} value={s.score?.[field] ?? 0} onChange={(e) => update(s._id, field, e.target.value)} /></td>)}<td className="px-5 py-4 font-extrabold">{total}</td></tr>; })}</tbody></table></div><div className="flex flex-wrap gap-3 p-5"><button disabled={saving} onClick={() => save(false)} className="rounded-lg bg-primary px-5 py-3 font-bold text-secondary">Save draft</button><button disabled={saving} onClick={() => save(true)} className="rounded-lg bg-button px-5 py-3 font-bold text-secondary">Submit for review</button></div></section>}</div>;
}
