import { useEffect, useState } from "react";
import API from "../../api/axios.jsx";
import { CLASS_SECTION_OPTIONS, formatClassSection } from "../../utils/classSections.js";

const defaultPolicy = { first_ca_max: 20, second_ca_max: 20, exam_max: 60 };

export default function SubjectManagement() {
  const [classes, setClasses] = useState([]); const [catalogue, setCatalogue] = useState([]); const [curriculum, setCurriculum] = useState([]); const [offerings, setOfferings] = useState([]); const [message, setMessage] = useState("");
  const [subjectForm, setSubjectForm] = useState({ name: "", code: "" });
  const [curriculumForm, setCurriculumForm] = useState({ section: "", subject_id: "", assessment_policy: defaultPolicy });
  const [offeringForm, setOfferingForm] = useState({ class_record: "", subject_id: "", assessment_policy: defaultPolicy });
  const [batchForm, setBatchForm] = useState({ class_record: "", subject_ids: [], assessment_policy: defaultPolicy });
  const load = async () => { const [c, s, l, o] = await Promise.all([API.get("/classes"), API.get("/subject-scores/subjects"), API.get("/subject-scores/level-curriculum"), API.get("/subject-scores/class-subjects")]); setClasses(c.data || []); setCatalogue(s.data || []); setCurriculum(l.data || []); setOfferings(o.data || []); };
  useEffect(() => { load().catch(() => setMessage("Unable to load subject setup.")); }, []);
  const addCatalogueSubject = async (e) => { e.preventDefault(); try { await API.post("/subject-scores/subjects", subjectForm); setSubjectForm({ name: "", code: "" }); setMessage("Subject added to the central catalogue."); await load(); } catch (x) { setMessage(x.response?.data?.message || "Unable to add subject."); } };
  const addCurriculumSubject = async (e) => { e.preventDefault(); try { await API.post("/subject-scores/level-curriculum", curriculumForm); setCurriculumForm({ section: "", subject_id: "", assessment_policy: defaultPolicy }); setMessage("Subject added to the level curriculum."); await load(); } catch (x) { setMessage(x.response?.data?.message || "Unable to save curriculum subject."); } };
  const addOffering = async (e) => { e.preventDefault(); try { await API.post("/subject-scores/class-subjects", offeringForm); setOfferingForm({ class_record: "", subject_id: "", assessment_policy: defaultPolicy }); setMessage("Class subject offering created."); await load(); } catch (x) { setMessage(x.response?.data?.message || "Unable to create the class subject offering."); } };
  const addBatchOfferings = async (e) => { e.preventDefault(); try { const result = await API.post("/subject-scores/class-subjects/batch", batchForm); setBatchForm({ class_record: "", subject_ids: [], assessment_policy: defaultPolicy }); setMessage(`${result.data.message}. ${result.data.skipped} existing subject(s) skipped.`); await load(); } catch (x) { setMessage(x.response?.data?.message || "Unable to create class-specific subjects."); } };
  const applyCurriculum = async (classId) => { try { const result = await API.post(`/subject-scores/level-curriculum/apply/${classId}`); setMessage(result.data.message); await load(); } catch (x) { setMessage(x.response?.data?.message || "Unable to apply curriculum."); } };
  const policyInput = (form, setForm, field, label) => <label className="text-sm font-semibold text-secondary/85">{label}<input required type="number" min="0" value={form.assessment_policy[field]} onChange={(e) => setForm({ ...form, assessment_policy: { ...form.assessment_policy, [field]: e.target.value } })} className="mt-1 block w-full rounded-lg border border-primary/10 bg-primary/5 px-3 py-2 text-primary" /></label>;
  const classLabel = (item) => `${item.session} — ${item.name.toUpperCase()}`;
  return <div className="px-6 py-8 lg:px-10"><h2 className="text-3xl font-extrabold text-secondary">Subject Setup</h2><p className="mt-3 text-secondary/75">Set the approved curriculum for Nursery, Basic, and Secondary first. Apply it to a class to create only the missing subject offerings; class-level additions remain possible.</p>{message && <p className="mt-5 rounded-lg bg-primary/10 p-4 font-semibold text-primary">{message}</p>}
    <div className="mt-8 grid gap-8 xl:grid-cols-2"><section className="rounded-xl bg-secondary p-6 shadow-lg"><h3 className="text-xl font-extrabold text-primary">1. Subject catalogue</h3><form onSubmit={addCatalogueSubject} className="mt-4 grid gap-3 md:grid-cols-3"><input required value={subjectForm.name} onChange={(e) => setSubjectForm({ ...subjectForm, name: e.target.value })} placeholder="Subject name" className="rounded-lg border border-primary/10 bg-primary/5 px-4 py-3 text-primary md:col-span-2" /><input value={subjectForm.code} onChange={(e) => setSubjectForm({ ...subjectForm, code: e.target.value })} placeholder="Code (optional)" className="rounded-lg border border-primary/10 bg-primary/5 px-4 py-3 text-primary" /><button className="rounded-lg bg-button px-5 py-3 font-bold text-secondary md:col-span-3">Add catalogue subject</button></form><div className="mt-5 flex flex-wrap gap-2">{catalogue.map((s) => <span key={s._id} className="rounded-full bg-primary/10 px-3 py-1 text-sm font-semibold text-primary">{s.name}{s.code ? ` (${s.code})` : ""}</span>)}</div></section>
      <section className="rounded-xl bg-secondary p-6 shadow-lg"><h3 className="text-xl font-extrabold text-primary">2. Level curriculum</h3><form onSubmit={addCurriculumSubject} className="mt-4 grid gap-3 md:grid-cols-2"><select required value={curriculumForm.section} onChange={(e) => setCurriculumForm({ ...curriculumForm, section: e.target.value })} className="rounded-lg border border-primary/10 bg-primary/5 px-4 py-3 text-primary"><option value="">Select academic level</option>{CLASS_SECTION_OPTIONS.map((item) => <option key={item.value} value={item.value}>{item.label}</option>)}</select><select required value={curriculumForm.subject_id} onChange={(e) => setCurriculumForm({ ...curriculumForm, subject_id: e.target.value })} className="rounded-lg border border-primary/10 bg-primary/5 px-4 py-3 text-primary"><option value="">Select catalogue subject</option>{catalogue.map((s) => <option key={s._id} value={s._id}>{s.name}</option>)}</select>{policyInput(curriculumForm, setCurriculumForm, "first_ca_max", "1st C.A. maximum")}{policyInput(curriculumForm, setCurriculumForm, "second_ca_max", "2nd C.A. maximum")}{policyInput(curriculumForm, setCurriculumForm, "exam_max", "Exam maximum")}<button className="rounded-lg bg-button px-5 py-3 font-bold text-secondary md:col-span-2">Add to level curriculum</button></form></section></div>
    <section className="mt-8 overflow-hidden rounded-xl bg-secondary shadow-lg"><div className="border-b border-primary/10 px-6 py-5"><h3 className="text-xl font-extrabold text-primary">Approved level curricula</h3></div><div className="overflow-x-auto"><table className="min-w-full"><thead className="bg-primary text-left text-xs font-bold uppercase text-secondary"><tr><th className="px-5 py-4">Level</th><th className="px-5 py-4">Subject</th><th className="px-5 py-4">Assessment policy</th></tr></thead><tbody>{curriculum.map((item) => { const p = item.assessment_policy || defaultPolicy; return <tr key={item._id} className="border-b border-primary/10 text-primary"><td className="px-5 py-4 font-bold">{formatClassSection(item.section)}</td><td className="px-5 py-4">{item.subject_record?.name}</td><td className="px-5 py-4">CA1 {p.first_ca_max}, CA2 {p.second_ca_max}, Exam {p.exam_max}</td></tr>; })}</tbody></table></div></section>
    <div className="mt-8 grid gap-8 xl:grid-cols-2"><section className="rounded-xl bg-secondary p-6 shadow-lg"><h3 className="text-xl font-extrabold text-primary">3. Apply a level curriculum</h3><p className="mt-2 text-primary/70">Applies the selected class’s level curriculum and skips subjects already offered to that class.</p><div className="mt-5 space-y-3">{classes.filter((c) => c.section).map((c) => <div key={c._id} className="flex flex-wrap items-center justify-between gap-3 rounded-lg bg-primary/5 p-4 text-primary"><span><b>{classLabel(c)}</b><span className="ml-2 text-sm text-primary/65">{formatClassSection(c.section)}</span></span><button onClick={() => applyCurriculum(c._id)} className="rounded-lg bg-button px-4 py-2 font-bold text-secondary">Apply curriculum</button></div>)}</div></section>
      <section className="rounded-xl bg-secondary p-6 shadow-lg"><h3 className="text-xl font-extrabold text-primary">4. Add one class-specific subject</h3><form onSubmit={addOffering} className="mt-4 grid gap-3 md:grid-cols-2"><select required value={offeringForm.class_record} onChange={(e) => setOfferingForm({ ...offeringForm, class_record: e.target.value })} className="rounded-lg border border-primary/10 bg-primary/5 px-4 py-3 text-primary"><option value="">Select class</option>{classes.map((c) => <option key={c._id} value={c._id}>{classLabel(c)}</option>)}</select><select required value={offeringForm.subject_id} onChange={(e) => setOfferingForm({ ...offeringForm, subject_id: e.target.value })} className="rounded-lg border border-primary/10 bg-primary/5 px-4 py-3 text-primary"><option value="">Select catalogue subject</option>{catalogue.map((s) => <option key={s._id} value={s._id}>{s.name}</option>)}</select>{policyInput(offeringForm, setOfferingForm, "first_ca_max", "1st C.A. maximum")}{policyInput(offeringForm, setOfferingForm, "second_ca_max", "2nd C.A. maximum")}{policyInput(offeringForm, setOfferingForm, "exam_max", "Exam maximum")}<button className="rounded-lg bg-button px-5 py-3 font-bold text-secondary md:col-span-2">Create class offering</button></form></section></div>
    <section className="mt-8 rounded-xl bg-secondary p-6 shadow-lg"><h3 className="text-xl font-extrabold text-primary">5. Batch-add class-specific subjects</h3><p className="mt-2 text-primary/70">For exceptions to the official curriculum. Existing class subjects are skipped automatically.</p><form onSubmit={addBatchOfferings} className="mt-4"><select required value={batchForm.class_record} onChange={(e) => setBatchForm({ ...batchForm, class_record: e.target.value })} className="w-full rounded-lg border border-primary/10 bg-primary/5 px-4 py-3 text-primary"><option value="">Select class</option>{classes.map((c) => <option key={c._id} value={c._id}>{classLabel(c)}</option>)}</select><div className="mt-4 grid gap-3 md:grid-cols-3">{policyInput(batchForm, setBatchForm, "first_ca_max", "1st C.A. maximum")}{policyInput(batchForm, setBatchForm, "second_ca_max", "2nd C.A. maximum")}{policyInput(batchForm, setBatchForm, "exam_max", "Exam maximum")}</div><div className="mt-4 grid max-h-52 gap-2 overflow-y-auto rounded-lg border border-primary/10 p-4 sm:grid-cols-2 lg:grid-cols-3">{catalogue.map((s) => <label key={s._id} className="flex cursor-pointer items-center gap-3 text-primary"><input type="checkbox" checked={batchForm.subject_ids.includes(s._id)} onChange={() => setBatchForm((form) => ({ ...form, subject_ids: form.subject_ids.includes(s._id) ? form.subject_ids.filter((id) => id !== s._id) : [...form.subject_ids, s._id] }))} className="h-4 w-4 accent-button" />{s.name}</label>)}</div><button className="mt-4 rounded-lg bg-button px-5 py-3 font-bold text-secondary">Add selected subjects</button></form></section>
    <section className="mt-8 overflow-hidden rounded-xl bg-secondary shadow-lg"><div className="border-b border-primary/10 px-6 py-5"><h3 className="text-xl font-extrabold text-primary">Class subject offerings</h3></div><div className="overflow-x-auto"><table className="min-w-full"><thead className="bg-primary text-left text-xs font-bold uppercase text-secondary"><tr><th className="px-5 py-4">Class</th><th className="px-5 py-4">Subject</th><th className="px-5 py-4">Assessment</th><th className="px-5 py-4">Current teacher</th></tr></thead><tbody>{offerings.map((s) => { const p = s.assessment_policy || defaultPolicy; return <tr key={s._id} className="border-b border-primary/10 text-primary"><td className="px-5 py-4">{s.session} — {s.class_record?.name?.toUpperCase()}</td><td className="px-5 py-4 font-bold">{s.subject_record?.name || s.subject}</td><td className="px-5 py-4">CA1 {p.first_ca_max}, CA2 {p.second_ca_max}, Exam {p.exam_max}</td><td className="px-5 py-4">{s.active_assignment?.teacher?.full_name || s.assigned_teacher?.full_name || "Unassigned"}</td></tr>; })}</tbody></table></div></section></div>;
}
